# Generated by Django 5.0.1 on 2024-01-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=20)),
                ('phone_no', models.CharField(max_length=12)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=40)),
                ('password1', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_no', models.PositiveIntegerField()),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.candidate')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting.users')),
            ],
        ),
    ]
