# Generated by Django 5.0 on 2024-01-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0002_alter_vote_user_name_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
