# Generated by Django 5.0.1 on 2024-01-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0003_rename_email_id_candidate_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
    ]
