# Generated by Django 5.0.1 on 2024-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Voting", "0004_remove_candidate_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_no",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
