# Generated by Django 5.0 on 2024-01-23 04:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0006_rename_vote_no_vote_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Votes',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='votes',
            new_name='vote',
        ),
    ]
