# Generated by Django 5.0.1 on 2024-01-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0007_rename_vote_votes_rename_votes_votes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='vote',
        ),
    ]
